name: "Repository Mirror: GitHub"

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: "Mirror"
    steps:
      - uses: pkgstore/github-action-mirror@main
        with:
          source_repo: "https://git.sr.ht/~martijnbraam/pyatem"
          source_user: "USER"
          source_token: "PASSWORD"
          target_repo: "https://github.com/git-2-github/martijnbraam-pyatem.git"
          target_user: "${{ secrets.MIRROR_TARGET_USER_GITHUB }}"
          target_token: "${{ secrets.MIRROR_TARGET_TOKEN_GITHUB }}"
